version: '3.7'

# TODO: There is no point to build this image dynamically.
#   Move the build process to infrastructure repo
services:
  dapi_envoy:
    build:
      context: ${PLATFORM_DAPI_ENVOY_DOCKER_BUILD_CONTEXT:?err}
      dockerfile: ${PLATFORM_DAPI_ENVOY_DOCKER_BUILD_DOCKER_FILE:?err}
      target: ${PLATFORM_DAPI_ENVOY_DOCKER_BUILD_TARGET}
      args:
        RUSTC_WRAPPER: "${RUSTC_WRAPPER}"
        SCCACHE_MEMCACHED: ${SCCACHE_MEMCACHED}
        SCCACHE_GHA_ENABLED: ${SCCACHE_GHA_ENABLED}
        ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL}
        ACTIONS_RUNTIME_TOKEN: ${ACTIONS_RUNTIME_TOKEN}
      cache_from:
        - ${CACHE_ENVOY_FROM:-${PLATFORM_DAPI_ENVOY_DOCKER_IMAGE}}
      cache_to:
        - ${CACHE_ENVOY_TO:-type=inline}
    image: dapi-envoy:local
